[package]
name = "svcheck"
version = "0.1.0"
edition = "2024"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.12.15", features = ["blocking", "rustls-tls"] }

[[bin]]
name = "svcheck"
path = "src/main.rs"
